import { Component, NgModule, OnInit, OnChanges, SimpleChanges, Input, Output, EventEmitter } from '@angular/core';
import { ReactiveFormsModule, FormGroup, FormControl, Validators, FormArray } from '@angular/forms';
import { TournamentMatch, TournamentMatchParticipant, TournamentPlayer, TournamentTeam } from '../../models/models';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSelectChange, MatSelectModule } from '@angular/material/select';

@Component({
  selector: 'tournament-submit-match-editor',
  templateUrl: './tournament_submit_match_editor.html',
  styleUrls: ['./tournament_submit_match_editor.scss']
})
export class TournamentSubmitMatchEditor implements OnInit, OnChanges {
  @Input() matches: TournamentMatch[] = [];
  @Input() match: TournamentMatch|undefined;
  @Input() requestInProgress: boolean = false;
  @Output() submit: EventEmitter<any> = new EventEmitter();

  idToNameMap: Map<string, string> = new Map();

  submitMatchForm: FormGroup;
  idFormControl: FormControl;
  participantsFormControl: FormArray;
  matchIdsFormControl: FormControl;
  generateMatchProgressionFormControl: FormControl;

  constructor() {
    this.idFormControl = new FormControl("", [Validators.required]);
    this.participantsFormControl = new FormArray<FormControl>([]);
    this.matchIdsFormControl = new FormControl("");
    this.generateMatchProgressionFormControl = new FormControl(false);
    this.submitMatchForm = new FormGroup({
      id: this.idFormControl,
      participants: this.participantsFormControl,
      matchIds: this.matchIdsFormControl,
      generateMatchProgression: this.generateMatchProgressionFormControl,
    });
  }

  ngOnInit() {
    this.refreshForm();
  }

  ngOnChanges(changes: SimpleChanges) {
    if ((changes["matches"] && JSON.stringify(changes["matches"].previousValue) !== JSON.stringify(changes["matches"].currentValue) ||
        (changes["matches"] && changes["matches"].previousValue !== changes["matches"].currentValue))) {
      this.refreshForm();
    }
  }

  get currentSelectedMatch(): TournamentMatch|undefined {
    if (this.match) return this.match;
    const matchId = this.idFormControl.value;
    return this.matches.find((match) => match._id === matchId);
  }

  refreshForm() {
    const theMatch = this.currentSelectedMatch;
    this.idToNameMap.clear();
    if (theMatch) {
      this.idFormControl.setValue(theMatch._id);
      this.getParticipantsFormArray().clear();
      for (let participant of (theMatch.participants || [])) {
        this.addParticipant(participant);
        this.idToNameMap.set(participant.playerOrTeam._id, "username" in participant.playerOrTeam ? participant.playerOrTeam.username : participant.playerOrTeam.name);
      }
      this.matchIdsFormControl.setValue(theMatch.matchIds.join(","));
      this.generateMatchProgressionFormControl.setValue(false);
    }
  }

  switchSelectedMatch(changeEvent: MatSelectChange) {
    this.refreshForm();
  }

  submitMatch() {
    const formValues = this.submitMatchForm.getRawValue();
    const matchIdsStrings: string[] = formValues.matchIds ? formValues.matchIds.split(",") : [];
    const matchIds: number[] = matchIdsStrings.map((matchId: string) => parseInt(matchId.trim().replace(/\D/g, "")));
    const submittedMatch = {
      id: formValues.id,
      participants: this.getParticipantsFormGroups().map((formGroup) => this.convertParticipantForm(formGroup)),
      matchIds,
      generateMatchProgression: formValues.generateMatchProgression,
    };
    this.submit.emit(submittedMatch);
  }

  hasChanges(): boolean {
    return JSON.stringify(this.currentSelectedMatch?.participants?.map(participant => this.simplifyParticipant(participant))) !==
           //JSON.stringify(this.participantsFormControl.value) ||
           JSON.stringify(this.getParticipantsFormGroups().map((formGroup) => this.convertParticipantForm(formGroup))) ||
      this.currentSelectedMatch?.matchIds.join(",") !== this.matchIdsFormControl.value;
  }

  simplifyParticipant(participant: TournamentMatchParticipant) {
    return {
      playerOrTeam: participant.playerOrTeam._id,
      score: participant.score,
      rolls: participant.rolls,
      bans: participant.bans,
      turnOrder: participant.turnOrder,
    };
  }

  // temporary: only 1 roll and ban for now, and also ignore picks for now since it'll be generated by backend
  convertParticipantForm(form: FormGroup): TournamentMatchParticipant {
    return {
      playerOrTeam: form.controls["playerOrTeam"].value,
      score: form.controls["score"].value,
      rolls: form.controls["roll"].value ? [form.controls["roll"].value] : undefined,
      bans: form.controls["ban"].value ? [form.controls["ban"].value] : undefined,
      turnOrder: form.controls["turnOrder"].value ? form.controls["turnOrder"].value : undefined,
    };
  }

  getParticipantsFormArray(): FormArray {
    return this.submitMatchForm.controls["participants"] as FormArray;
  }

  getParticipantsFormGroups(): FormGroup[] {
    return this.getParticipantsFormArray().controls as FormGroup[];
  }

  addParticipant(participant: TournamentMatchParticipant|undefined = undefined) {
    const participantPlayerOrTeamFormControl = new FormControl(participant?.playerOrTeam._id || "", [Validators.required]);
    const participantScoreFormControl = new FormControl(participant?.score || 0, [Validators.required]);
    const participantRollFormControl = new FormControl(participant?.rolls?.[0]);
    const participantBanFormControl = new FormControl(participant?.bans?.[0]);
    const participantTurnOrderFormControl = new FormControl(participant?.turnOrder);
    const participantForm = new FormGroup({
      playerOrTeam: participantPlayerOrTeamFormControl,
      score: participantScoreFormControl,
      roll: participantRollFormControl,
      ban: participantBanFormControl,
      turnOrder: participantTurnOrderFormControl,
    });
    this.getParticipantsFormArray().push(participantForm);
  }
}

@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    MatButtonModule,
    MatCheckboxModule,
    MatFormFieldModule,
    MatIconModule,
    MatInputModule,
    MatSelectModule,
  ],
  declarations: [ TournamentSubmitMatchEditor ],
  exports:      [ TournamentSubmitMatchEditor ],
  bootstrap:    [ TournamentSubmitMatchEditor ]
})
export class TournamentSubmitMatchEditorModule {}